# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        gallery_thumb:
            quality: 90
            filters:
                thumbnail: { size: [ 200, 200 ], mode: fixed }
        avatar_thumb:
            quality: 90
            filters:
                thumbnail: { size: [ 100, 100 ], mode: fixed }
        user_cover:
            quality: 90
            filters:
                thumbnail: { size: [ 1500, 500 ], mode: fixed }

        gallery_image_filter_full:
#            data_loader: flysystem_loader
            filters:
                downscale:
                    max: [1500, 1500]
#            post_processors:
#                jpegoptim: { strip_all: true, max: 100, progressive: true }
#                optipng: { strip_all: true, level: 5 }

        gallery_image_filter_medium:
#            data_loader: flysystem_loader
            filters:
                downscale:
                    max: [500, 500]
            post_processors:
                jpegoptim: { strip_all: true, max: 75, progressive: true }
                optipng: { strip_all: true, level: 5 }

        gallery_image_filter_small:
#            data_loader: flysystem_loader
            filters:
                downscale:
                    max: [200, 200]
            post_processors:
                jpegoptim: { strip_all: true, max: 10, progressive: true }
                optipng: { strip_all: true, level: 5 }
    loaders:
        local_images:
            flysystem:
                filesystem_service: League\Flysystem\FilesystemOperator

    data_loader: local_images

    resolvers:
        gallery_thumb:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url:           '%uploads_base_url%'
                cache_prefix:       media/cache
                visibility:         public

        avatar_thumb:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: '%uploads_base_url%'
                cache_prefix: media/cache
                visibility: public
