talav_user:
  login_route: talav_user_login
  signup_success_route: user_profile_edit
  resources:
    user:
      classes:
        model: Groshy\Entity\User
    user_oauth:
      classes:
        model: Groshy\Entity\UserOAuth
  email:
    from:
      email: samsung.android1890i@gmail.com
      name: Samsung Android
  registration:
    form:
      type: Groshy\Form\Type\RegistrationFormType
      model: Groshy\Form\Model\RegistrationFormModel
  login:
    options:
      username_parameter: talav_type_user_user_login[username]
      password_parameter: talav_type_user_user_login[password]
      enable_csrf: true
      csrf_parameter: talav_type_user_user_login[_csrf_token]

talav_permission:
  resources:
    role:
      classes:
        model: Groshy\Entity\Role
    permission:
      classes:
        model: Groshy\Entity\Permission

talav_profile:
  resources:
    profile:
      classes:
        model: Groshy\Entity\Profile

talav_settings:
  resources:
    settings:
      classes:
        model: Groshy\Entity\Settings
  settings:
    registration_enabled:
      type: boolean
      scope: tenant
      value: true
    site.name:
      type: string
      scope: global
    site.version:
      type: string
      scope: global
    meta.keywords:
      type: string
      scope: global
    meta.description:
      type: string
      scope: global
    contact.email:
      type: string
      scope: global
    contact.support_email:
      type: string
      scope: global
    contact.no_reply_email:
      type: string
      scope: global
    other.google_analytics_code:
      type: string
      scope: global

auto_mapper_plus:
  options:
    create_unregistered_mappings: true

#oneup_flysystem:
#  adapters:
#    default:
#      local:
#        location: "%kernel.project_dir%/public/media"
#  filesystems:
#    default:
#      adapter: default
