talav_user:
    login_route: talav_user_login
    signup_success_route: user_profile_edit
    resources:
        user:
            classes:
                model: Groshy\Entity\User
        user_oauth:
            classes:
                model: Groshy\Entity\UserOAuth
    email:
        from:
            email: samsung.android1890i@gmail.com
            name: Samsung Android
    registration:
        form:
            type: Groshy\Form\Type\RegistrationFormType
            model: Groshy\Form\Model\RegistrationFormModel
    login:
        options:
            username_parameter: talav_type_user_user_login[username]
            password_parameter: talav_type_user_user_login[password]
            enable_csrf: true
            csrf_parameter: talav_type_user_user_login[_csrf_token]

talav_permission:
    resources:
        role:
            classes:
                model: Groshy\Entity\Role
        permission:
            classes:
                model: Groshy\Entity\Permission

    # --------------------------------------------------------------------------------
    # PERMISSIONS
    # --------------------------------------------------------------------------------
    permissions:
        # mapping a "set name" to an array of "permission names"
        sets:
            ACTIVITIES: ['view_activity','create_activity','edit_activity','budget_activity','time_activity','delete_activity','permissions_activity']
            ACTIVITIES_ALL_TEAMLEAD: ['view_teamlead_activity','edit_teamlead_activity','budget_teamlead_activity','time_teamlead_activity','permissions_teamlead_activity']
            ACTIVITIES_ALL_TEAM: ['view_team_activity','edit_team_activity','budget_team_activity','time_team_activity']
            ACTIVITIES_TEAMLEAD: ['view_teamlead_activity','create_activity','edit_teamlead_activity','budget_teamlead_activity','time_teamlead_activity']
            PROJECTS: ['view_project','create_project','edit_project','budget_project','time_project','delete_project','permissions_project','comments_project','details_project']
            PROJECTS_ALL_TEAMLEAD: ['view_teamlead_project','edit_teamlead_project','budget_teamlead_project','time_teamlead_project','permissions_teamlead_project','comments_teamlead_project','details_teamlead_project']
            PROJECTS_ALL_TEAM: ['view_team_project','edit_team_project','budget_team_project','time_team_project','comments_team_project','details_team_project']
            PROJECTS_TEAMLEAD: ['view_teamlead_project','budget_teamlead_project','time_teamlead_project','comments_teamlead_project','details_teamlead_project']
            CUSTOMERS: ['view_customer','create_customer','edit_customer','budget_customer','time_customer','delete_customer','permissions_customer','comments_customer','details_customer']
            CUSTOMERS_ALL_TEAMLEAD: ['view_teamlead_customer','edit_teamlead_customer','budget_teamlead_customer','time_teamlead_customer','permissions_teamlead_customer','comments_teamlead_customer','details_teamlead_customer']
            CUSTOMERS_ALL_TEAM: ['view_team_customer','edit_team_customer','budget_team_customer','time_team_customer','comments_team_customer','details_team_customer']
            CUSTOMERS_TEAMLEAD: ['view_teamlead_customer','budget_teamlead_customer','time_teamlead_customer','comments_teamlead_customer','details_teamlead_customer']
            INVOICE: ['view_invoice','create_invoice']
            INVOICE_ADMIN: ['manage_invoice_template']
            INVOICE_ALL: ['delete_invoice']
            TIMESHEET: ['view_own_timesheet','start_own_timesheet','stop_own_timesheet','create_own_timesheet','edit_own_timesheet','export_own_timesheet','delete_own_timesheet','weekly_own_timesheet']
            TIMESHEET_OTHER: ['view_other_timesheet','start_other_timesheet','stop_other_timesheet','create_other_timesheet','edit_other_timesheet','export_other_timesheet','delete_other_timesheet']
            PROFILE: ['view_own_profile','edit_own_profile','password_own_profile','preferences_own_profile','api-token_own_profile']
            PROFILE_OTHER: ['view_other_profile','edit_other_profile','password_other_profile','roles_other_profile','preferences_other_profile','api-token_other_profile','teams_other_profile','supervisor_other_profile']
            TAGS: ['view_tag','manage_tag','create_tag','delete_tag']
            USER: ['view_user','create_user','delete_user','role_permissions']
            RATE: ['view_rate_own_timesheet','edit_rate_own_timesheet']
            RATE_OTHER: ['view_rate_other_timesheet','edit_rate_other_timesheet']
            EXPORT: ['create_export','edit_export_own_timesheet','edit_export_other_timesheet']
            BILLABLE: ['edit_billable_own_timesheet','edit_billable_other_timesheet']
            TEAMS: ['view_team','create_team','edit_team','delete_team']
            LOCKDOWN: ['lockdown_grace_timesheet','lockdown_override_timesheet']
            REPORTING: ['view_reporting','view_other_reporting','project_reporting','customer_reporting']
            # permissions which are deactivated, as these features are hidden for now
            # brave users can try to activate them and be surprised what happens
            REGISTER_BETA: []
        # mapping a "role name" to an array of "set names"
        maps:
            ROLE_USER: ['TIMESHEET','PROFILE']
            ROLE_TEAMLEAD: ['ACTIVITIES_TEAMLEAD','PROJECTS_TEAMLEAD','CUSTOMERS_TEAMLEAD','TIMESHEET_OTHER','INVOICE','TIMESHEET','PROFILE','EXPORT','BILLABLE','TAGS','REPORTING']
            ROLE_ADMIN: ['ACTIVITIES','PROJECTS','CUSTOMERS','INVOICE','INVOICE_ADMIN','TIMESHEET','TIMESHEET_OTHER','PROFILE','TEAMS','RATE','RATE_OTHER','EXPORT','BILLABLE','TAGS','LOCKDOWN','REPORTING']
            ROLE_SUPER_ADMIN: ['ACTIVITIES','PROJECTS','CUSTOMERS','INVOICE','INVOICE_ADMIN','TIMESHEET','TIMESHEET_OTHER','PROFILE','PROFILE_OTHER','USER','TEAMS','RATE','RATE_OTHER','EXPORT','BILLABLE','TAGS','LOCKDOWN','REPORTING']
        # mapping a "role name" to an array of "permission names"
        roles:
            ROLE_USER: ['view_team_member','time_team_project','create_tag','view_reporting']
            ROLE_TEAMLEAD: ['view_rate_own_timesheet','view_rate_other_timesheet','hourly-rate_own_profile','view_team_member']
            ROLE_ADMIN: ['hourly-rate_own_profile','edit_exported_timesheet','teams_own_profile','view_team_member','view_all_data','contract_other_profile']
            ROLE_SUPER_ADMIN: ['hourly-rate_own_profile','hourly-rate_other_profile','roles_own_profile','supervisor_own_profile','system_information','system_configuration','plugins','edit_exported_timesheet','teams_own_profile','view_team_member','upload_invoice_template','view_all_data','contract_other_profile']
# --------------------------------------------------------------------------------


talav_profile:
    resources:
        profile:
            classes:
                model: Groshy\Entity\Profile
        user_relation:
            classes:
                model: Groshy\Entity\UserRelation
        user_friend:
            classes:
                model: Groshy\Entity\UserFriend
        friendship:
            classes:
                model: Groshy\Entity\Friendship
        friendship_request:
            classes:
                model: Groshy\Entity\FriendshipRequest

talav_settings:
    resources:
        settings:
            classes:
                model: Groshy\Entity\Settings
    settings:
        registration_enabled:
            type: boolean
            scope: tenant
            value: true
        site.name:
            type: string
            scope: global
        site.version:
            type: string
            scope: global
        meta.keywords:
            type: string
            scope: global
        meta.description:
            type: string
            scope: global
        contact.email:
            type: string
            scope: global
        contact.support_email:
            type: string
            scope: global
        contact.no_reply_email:
            type: string
            scope: global
        other.google_analytics_code:
            type: string
            scope: global

talav_media:
    resources:
        media:
            classes:
                model: Groshy\Entity\Media
                manager: Talav\Component\Media\Manager\MediaManager
                repository: Talav\Component\Resource\Repository\ResourceRepository
    providers:
        file:
            service: talav.media.provider.file
            generator: talav.media.generator.uuid
            filesystem: oneup_flysystem.default_filesystem
            cdn: talav.media.cdn.server
            constraints:
                extensions: [
                    'pdf', 'txt', 'rtf','doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
                    'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml'
                ]
                file_constraints:
                    mimeTypes: [
                        'application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain',
                        'application/excel', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
                        'application/vnd.ms-powerpoint', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.graphics', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.chart', 'application/vnd.oasis.opendocument.formula', 'application/vnd.oasis.opendocument.database', 'application/vnd.oasis.opendocument.image',
                        'text/comma-separated-values', 'text/xml', 'application/xml', 'application/zip',
                    ]
        image:
            service: talav.media.provider.image
            generator: talav.media.generator.uuid
            filesystem: oneup_flysystem.default_filesystem
            cdn: talav.media.cdn.server
            thumbnail: talav.media.thumbnail.glide
            constraints:
                extensions: [ 'jpg', 'png', 'jpeg' ]
                file_constraints:
                    mimeTypes: [ 'image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png' ]
                # both parameters are merged internally so image parameters override file parameters with the same key
                image_constraints:
                    minWidth: 100
                    minHeight: 100
                    maxWidth: 3000
                    maxHeight: 3000

    contexts:
        avatar:
            providers:
                - talav.media.provider.image
            formats:
                large:
                    w: 300
                    h: 300
                medium:
                    w: 200
                    h: 200
                square_medium:
                    w: 200
                    h: 200
                    fit: crop
                small:
                    w: 120
                    h: 120
                square_small:
                    w: 120
                    h: 120
                    fit: crop

        cover:
            providers:
                - talav.media.provider.image
            formats:
                user_cover:
                    w: 1500
                    h: 500
                    fit: crop

        doc:
            providers:
                - talav.media.provider.file

    cdn:
        server:
            path: /uploads/media


auto_mapper_plus:
    options:
        create_unregistered_mappings: true

#oneup_flysystem:
#  adapters:
#    default:
#      local:
#        location: "%kernel.project_dir%/public/media"
#  filesystems:
#    default:
#      adapter: default
