framework:
    workflows:
#        order_processing:
#            type: 'state_machine'
#            audit_trail:
#                enabled: true
#            marking_store:
#                type: 'method'
#                property: 'status'
#            supports:
#                - App\Entity\Order
#            initial_marking: !php/const App\Entity\Order::PENDING
#            places:
#                - !php/const App\Entity\Order::PENDING
#                - !php/const App\Entity\Order::PROCESSING
#                - !php/const App\Entity\Order::COMPLETED
#                - !php/const App\Entity\Order::CANCELLED
#            transitions:
#                to_completed:
#                    from: !php/const App\Entity\Order::PENDING
#                    to: !php/const App\Entity\Order::COMPLETED
#                to_cancel:
#                    from: [ !php/const App\Entity\Order::PENDING, !php/const App\Entity\Order::PROCESSING ]
#                    to: !php/const App\Entity\Order::CANCELLED
#        payment_processing:
#            type: 'state_machine'
#            audit_trail:
#                enabled: true
#            marking_store:
#                type: 'method'
#                property: 'status'
#            supports:
#                - App\Entity\Payment
#            initial_marking: !php/const App\Entity\Payment::PENDING
#            places:
#                - !php/const App\Entity\Payment::PENDING
#                - !php/const App\Entity\Payment::PROCESSING
#                - !php/const App\Entity\Payment::COMPLETED
#                - !php/const App\Entity\Payment::CANCELLED
#            transitions:
#                to_confirm:
#                    from: !php/const App\Entity\Payment::PENDING
#                    to: !php/const App\Entity\Payment::COMPLETED
#                to_cancel:
#                    from: !php/const App\Entity\Payment::PENDING
#                    to: !php/const App\Entity\Payment::CANCELLED
        registration:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - Groshy\Entity\User
                - Groshy\Entity\Profile
                - Talav\ProfileBundle\Entity\ProfileInterface
            initial_marking: !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_PERSONAL_INFO->value
            places:
                - !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_PERSONAL_INFO->value
                - !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_ACCOUNT_INFO->value
                - !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_COMPLETE->value
            transitions:
                to_account:
                    from: !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_PERSONAL_INFO->value
                    to: !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_ACCOUNT_INFO->value
                to_complete:
                    from: !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_ACCOUNT_INFO->value
                    to: !php/enum Talav\UserBundle\Enum\RegistrationWorkflowEnum::STATE_COMPLETE->value

