# Put parameters here that don't need to change on each machine where the application is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    patterns.path: '.+'
    patterns.page: '[1-9](\d*)'
    patterns.id: '\d+'
    patterns.slug: '[^/]+'

    translation_domain: 'TalavWebBundle'

    # fixed
    locale:             en
    # the original list of all locales is the next line, it can be used to regenerate the locale list in case new locales will be added
    app_locales:        ar|cs|da|de|el|en|eo|es|eu|fa|fi|fo|fr|he|hr|hu|it|ja|ko|nb_NO|nl|pl|pt|pt_BR|ro|ru|sk|sv|tr|uk|vi|zh_CN|zh_Hant|cs_CZ|da_DK|da_GL|de_AT|de_BE|de_CH|de_DE|de_IT|de_LI|de_LU|el_CY|el_GR|en_AE|en_AG|en_AI|en_AS|en_AT|en_AU|en_BB|en_BE|en_BI|en_BM|en_BS|en_BW|en_BZ|en_CA|en_CC|en_CH|en_CK|en_CM|en_CX|en_CY|en_DE|en_DK|en_DM|en_ER|en_FI|en_FJ|en_FK|en_FM|en_GB|en_GD|en_GG|en_GH|en_GI|en_GM|en_GU|en_GY|en_HK|en_IE|en_IL|en_IM|en_IN|en_IO|en_JE|en_JM|en_KE|en_KI|en_KN|en_KY|en_LC|en_LR|en_LS|en_MG|en_MH|en_MO|en_MP|en_MS|en_MT|en_MU|en_MV|en_MW|en_MY|en_NA|en_NF|en_NG|en_NL|en_NR|en_NU|en_NZ|en_PG|en_PH|en_PK|en_PN|en_PR|en_PW|en_RW|en_SB|en_SC|en_SD|en_SE|en_SG|en_SH|en_SI|en_SL|en_SS|en_SX|en_SZ|en_TC|en_TK|en_TO|en_TT|en_TV|en_TZ|en_UG|en_UM|en_US|en_VC|en_VG|en_VI|en_VU|en_WS|en_ZA|en_ZM|en_ZW|es_AR|es_BO|es_BR|es_BZ|es_CL|es_CO|es_CR|es_CU|es_DO|es_EC|es_ES|es_GQ|es_GT|es_HN|es_MX|es_NI|es_PA|es_PE|es_PH|es_PR|es_PY|es_SV|es_US|es_UY|es_VE|eu_ES|fa_AF|fa_IR|fi_FI|fo_DK|fo_FO|fr_BE|fr_BF|fr_BI|fr_BJ|fr_BL|fr_CA|fr_CD|fr_CF|fr_CG|fr_CH|fr_CI|fr_CM|fr_DJ|fr_DZ|fr_FR|fr_GA|fr_GF|fr_GN|fr_GP|fr_GQ|fr_HT|fr_KM|fr_LU|fr_MA|fr_MC|fr_MF|fr_MG|fr_ML|fr_MQ|fr_MR|fr_MU|fr_NC|fr_NE|fr_PF|fr_PM|fr_RE|fr_RW|fr_SC|fr_SN|fr_SY|fr_TD|fr_TG|fr_TN|fr_VU|fr_WF|fr_YT|he_IL|hr_BA|hr_HR|hu_HU|it_CH|it_IT|it_SM|it_VA|ja_JP|ko_KP|ko_KR|nl_AW|nl_BE|nl_BQ|nl_CW|nl_NL|nl_SR|nl_SX|pl_PL|pt_AO|pt_CH|pt_CV|pt_GQ|pt_GW|pt_LU|pt_MO|pt_MZ|pt_PT|pt_ST|pt_TL|ro_MD|ro_RO|ru_BY|ru_KG|ru_KZ|ru_MD|ru_RU|ru_UA|sk_SK|sv_AX|sv_FI|sv_SE|tr_CY|tr_TR|vi_VN
    app_name:           TalavApp
    app_version:        1.0.0
    app_owner:          talav.com
    app_owner_url:      https://www.demoapp.dvl.to
    app_owner_city:     Montévraz
    app_description:    Talav Demo App.

    app_paginate_maxperpage: 10

    app_secret:         '%env(string:APP_SECRET)%'
    app_mode:           '%env(string:APP_MODE)%'

    # mailer
    mailer_user_name: Calculation
    mailer_user_email: calculation@bibi.nu

    # cookies
    cookie_path: '%env(string:COOKIE_PATH)%'

    # keys
    google_translator_key: '%env(string:GOOGLE_TRANSLATOR_KEY)%'
    google_recaptcha_secret_key: '%env(string:GOOGLE_RECAPTCHA_SECRET_KEY)%'
    google_recaptcha_site_key: '%env(string:GOOGLE_RECAPTCHA_SITE_KEY)%'

    #links
    link_dev: '%env(string:LINK_DEV)%'
    link_prod: '%env(string:LINK_PROD)%'

    # uploads
    uploads_dir_name: 'uploads'
    uploads_base_url: '/%uploads_dir_name%'

    # media
    media_dir_name: 'media'
    media_base_url: '%uploads_base_url%/%media_dir_name'

    # optimize
    .container.dumper.inline_factories: true

    # the date format for log
    log_date_format: 'd.m.Y H:i:s.v'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Groshy\:
        resource: '../src/'
        exclude:
            - '../src/Config/'
            - '../src/Controller/'
            - '../src/Repository/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Groshy\Api\Action\:
        resource: '../src/Api/Action'
        tags: ['controller.service_arguments']
    Groshy\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    pagerfanta.view.default:
        class: Talav\WebBundle\Pagerfanta\View
        tags:
            - { name: pagerfanta.view, alias: default }

    Groshy\Menu\SidebarMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createAssetSidebarMenu, alias: asset_sidebar_menu }
            - { name: knp_menu.menu_builder, method: createLiabilitiesSidebarMenu, alias: liability_sidebar_menu }
    Groshy\Menu\BreadcrumbsMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: buildDashboardMenu, alias: breadcrumbs_dashboard }
            - { name: knp_menu.menu_builder, method: buildAssetTypeMenu, alias: breadcrumbs_asset_type }
            - { name: knp_menu.menu_builder, method: buildPositionMenu, alias: breadcrumbs_position }
    Groshy\Routing\DateParamRouter:
        decorates: 'router'
        arguments: ['@Groshy\Routing\DateParamRouter.inner']
